#[allow(non_camel_case_types)]
///Auto-generated by `deno_ops`, i.e: `#[op]`
///
///Use `op_string_length::decl()` to get an op-declaration
///you can include in a `deno_core::Extension`.
pub struct op_string_length;
#[doc(hidden)]
impl op_string_length {
    pub fn name() -> &'static str {
        stringify!(op_string_length)
    }
    pub fn v8_fn_ptr<'scope>() -> deno_core::v8::FunctionCallback {
        use deno_core::v8::MapFnTo;
        Self::v8_func.map_fn_to()
    }
    pub fn decl<'scope>() -> deno_core::OpDecl {
        deno_core::OpDecl {
            name: Self::name(),
            v8_fn_ptr: Self::v8_fn_ptr(),
            enabled: true,
            fast_fn: None,
            is_async: false,
            is_unstable: false,
            is_v8: false,
        }
    }
    #[inline]
    #[allow(clippy::too_many_arguments)]
    fn call(string: &str) -> Result<u32, AnyError> {
        Ok(string.len() as u32)
    }
    pub fn v8_func<'scope>(
        scope: &mut deno_core::v8::HandleScope<'scope>,
        args: deno_core::v8::FunctionCallbackArguments,
        mut rv: deno_core::v8::ReturnValue,
    ) {
        let ctx = unsafe {
            &*(deno_core::v8::Local::<deno_core::v8::External>::cast(args.data()).value()
                as *const deno_core::_ops::OpCtx)
        };
        let arg_0 = match deno_core::v8::Local::<
            deno_core::v8::String,
        >::try_from(args.get(0usize as i32)) {
            Ok(v8_string) => deno_core::serde_v8::to_utf8(v8_string, scope),
            Err(_) => {
                return deno_core::_ops::throw_type_error(
                    scope,
                    format!("Expected string at position {}", 0usize),
                );
            }
        };
        let arg_0 = arg_0.as_ref();
        let result = Self::call(arg_0);
        let op_state = ::std::cell::RefCell::borrow(&*ctx.state);
        op_state.tracker.track_sync(ctx.id);
        match result {
            Ok(result) => {
                rv.set_uint32(result as u32);
            }
            Err(err) => {
                let exception = deno_core::error::to_v8_error(
                    scope,
                    op_state.get_error_class_fn,
                    &err,
                );
                scope.throw_exception(exception);
            }
        };
    }
}
